server:
  port: 8082
spring:
  application:
    name: consumer
  cloud:
    function:
      definition: processRiderLocation;processRiderStatus
    stream:
      function:
        definition: processRiderLocation;processRiderStatus
      bindings:
        processRiderLocation-in-0:
          destination: my-topic
          group: rider-location-grp
        processRiderStatus-in-0:
          destination: new-topic
          group: rider-status-grp
    kafka:
      binder:
        brokers: localhost:9092


